FROM debian:stretch-slim
WORKDIR /root/
RUN mkdir /configuration-profiles
RUN mkdir -p .local/share .config
RUN ln -s /configuration-profiles .local/share/medchain
RUN ln -s /configuration-profiles .config/medchain
RUN apt update; apt install -y procps ca-certificates; apt clean
COPY run_nodes.sh .
COPY exe/conode.Linux.x86_64 ./medchain

EXPOSE 7770 7771

CMD ["./run_nodes.sh", "-d", "/configuration-profiles", "-v", "2"]
