Simulation = "MedChainService"
Servers = 3
BF = 2
Depth = 5
Rounds = 5
Suite = "Ed25519"
Bandwidth = 100
RunWait = "2h"
Delay = 20
BatchSize = 5

Keep,   Queries,  Hosts,      BlockInterval         
false,     1,          5,             "1s"
false,     1,          10,            "1s"
false,     1,          20,            "1s"
false,     1,          30,            "1s"

