FROM debian:stretch-slim
RUN apt update && apt install -y procps ca-certificates && apt clean
WORKDIR /root/
RUN mkdir /medchain_data
RUN mkdir /medchain-configuration
RUN mkdir -p .local/share .config
RUN ln -s /medchain_data .local/share/medchain
RUN ln -s /medchain_data .config/medchain

EXPOSE 7770 7771
